name: Run bot
run-name: Re-run bot when new code is added 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SparkedHost
        if: github.ref == 'refs/heads/main'
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://control.sparkedhost.us/api/client/servers/29562251/power"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "Accept": "application/json", "Authorization": "Bearer ${{ secrets.SPARKEDKEY }}"}'
          data: '{"signal": "restart"}'
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORDWEBHOOK }}
          embed-title: "PUSH Manager"
          embed-description: "New version of SMOBOT is running"
          embed-color: 7419530
          embed-timestamp: ${{ github.event.repository.updated_at}}
          embed-footer-icon-url: "https://i.ibb.co/vs7BpgP/ss.png"
          embed-footer-text: "powered by APIBot"
          embed-author-name: "PUSH Manager (BETA)"
          embed-author-icon-url: "https://i.ibb.co/vs7BpgP/ss.png"
