name: Run bot
run-name: Re-run bot when new code is added 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SparkedHost
        if: github.ref == 'refs/heads/main'
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://control.sparkedhost.us/api/client/servers/29562251/power"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "Accept": "application/json", "Authorization": "Bearer ${{ secrets.SPARKEDKEY }}"}'
          data: '{"signal": "restart"}'
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORDWEBHOOK }}
          embeds:
            '[{"title":"PUSH Manager","description":"New version of SMOBOT is running","color": "7419530", timestamp: ${{ github.event.repository.updated_at}}, "footer": {"icon_url": "https://i.ibb.co/vs7BpgP/ss.png",
            "text": "powered by SMObot"},"author": {"name": "PUSH Manager (BETA)",
            "icon_url": "https://i.ibb.co/vs7BpgP/ss.png"} }]'
